modifying conversion function call to include requirements.txt in security.yml

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -82,7 +82,7 @@ jobs:
         if: ${{ env.Vulnerabilities_found == 'true' }}
         run: |
           echo "Converting safety_output.json to SARIF"
-          python scripts/convert_safety_to_sarif.py ./scan-results/safety_output.json ./scan-results/safety_output.sarif || echo "SARIF conversion failed"
+          python scripts/convert_safety_to_sarif.py ./scan-results/safety_output.json ./scan-results/safety_output.sarif ./requirements.txt || echo "SARIF conversion failed"
           echo "Conversion complete."
 
       # Debug step: Check if SARIF file was created.
